function H = visualizeMosaicResponseAlongMeridian(...
    indicesOfConesAlongMeridian, identitiesOfConesAlongMeridian, ...
    coordsOfConesAlongMeridian, ...
    spatialActivationMap, tickDegs, spaceLimitsDegs, figureTitle)

H = vcNewGraphWin();

% Retrieve the indices of L-, M- and S-cones along the vertical meridian
lConeIndices = find(identitiesOfConesAlongMeridian == 2);
mConeIndices = find(identitiesOfConesAlongMeridian == 3);
sConeIndices = find(identitiesOfConesAlongMeridian == 4);

% Drop the edge
% lConeIndices = lConeIndices(1:(end-2));

plot(coordsOfConesAlongMeridian(lConeIndices), ...
    spatialActivationMap(indicesOfConesAlongMeridian(lConeIndices)), ...
    'ro', 'MarkerFaceColor', [1 0.5 0.5], 'MarkerSize', 8);
plot(coordsOfConesAlongMeridian(mConeIndices), ...
    spatialActivationMap(indicesOfConesAlongMeridian(mConeIndices)), ...
    'go', 'MarkerFaceColor', [0.5 1 0.5], 'MarkerSize', 8);
plot(coordsOfConesAlongMeridian(sConeIndices), ...
    spatialActivationMap(indicesOfConesAlongMeridian(sConeIndices)), ...
    'bo', 'MarkerFaceColor', [0.5 0.5 1], 'MarkerSize', 8);
box on;
set(gca, 'XTick', tickDegs, 'XTickLabel', sprintf('%2.1f\n', tickDegs), ...
    'XLim', spaceLimitsDegs, 'YLim',...
    [0 max(spatialActivationMap(indicesOfConesAlongMeridian(lConeIndices)))], ...
    'FontSize', 14);
box on; grid on
axis 'square'
xlabel('\it space (degs)');
ylabel('\it cone excitation');
title(figureTitle);

end